[2025-06-25 18:47:57,281] - INFO - core - YAML successfully loaded from: 'config/config.yaml'
[2025-06-25 18:47:57,930] - INFO - core - YAML successfully loaded from: 'config/params.yaml'
[2025-06-25 18:47:58,201] - INFO - core - YAML successfully loaded from: 'config/schema.yaml'
[2025-06-25 18:47:58,479] - INFO - core - YAML successfully loaded from: 'config/templates.yaml'
[2025-06-25 18:47:58,747] - INFO - s3_handler - S3Handler initialized for bucket 'studentperformance-dev-artifacts' in region 'us-east-1'
[2025-06-25 18:47:59,021] - INFO - model_prediction - Initializing ModelPrediction.
[2025-06-25 18:47:59,293] - INFO - model_prediction - Loading inference model from local path.
[2025-06-25 18:48:00,152] - INFO - core - Inference Model loaded from: 'inference_model/inference_model.joblib'
[2025-06-25 18:48:10,054] - INFO - model_prediction - Running prediction using inference model.
[2025-06-25 18:48:10,761] - INFO - model_prediction - Saved predictions locally at predictions\20250625T174759Z\20250625T174759Z_preds.csv
[2025-06-25 18:48:11,019] - INFO - s3_handler - S3Handler context entered
[2025-06-25 18:48:11,305] - INFO - s3_handler - S3Handler context exited
[2025-06-25 18:48:11,578] - ERROR - model_prediction - Failed to save predictions.
Traceback (most recent call last):
  File "E:\MyProjects\student_performance\src\student_performance\components\model_prediction.py", line 93, in save_predictions
    handler.stream_dataframe(pred_df, s3_key)
AttributeError: 'S3Handler' object has no attribute 'stream_dataframe'
[2025-06-25 18:48:11,854] - ERROR - exception - Error occurred in file [E:\MyProjects\student_performance\src\student_performance\components\model_prediction.py], line [93], message: ['S3Handler' object has no attribute 'stream_dataframe']
Traceback (most recent call last):
  File "E:\MyProjects\student_performance\src\student_performance\components\model_prediction.py", line 93, in save_predictions
    handler.stream_dataframe(pred_df, s3_key)
AttributeError: 'S3Handler' object has no attribute 'stream_dataframe'
[2025-06-25 18:48:12,125] - ERROR - app - StudentPerformanceError during prediction.
Traceback (most recent call last):
  File "E:\MyProjects\student_performance\src\student_performance\components\model_prediction.py", line 93, in save_predictions
    handler.stream_dataframe(pred_df, s3_key)
AttributeError: 'S3Handler' object has no attribute 'stream_dataframe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\MyProjects\student_performance\app.py", line 51, in predict
    predictor.save_predictions(predictions)
  File "E:\MyProjects\student_performance\src\student_performance\components\model_prediction.py", line 100, in save_predictions
    raise StudentPerformanceError(e, logger) from e
src.student_performance.exception.exception.StudentPerformanceError: Error occurred in file [E:\MyProjects\student_performance\src\student_performance\components\model_prediction.py], line [93], message: ['S3Handler' object has no attribute 'stream_dataframe']
